name: Backend tests

on:
  workflow_call:
    inputs:
      ref:
        description: The reference to test
        type: string
        required: true
      image:
        description: The name of the image to test
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      db:
        image: postgres:14.1
        env:
          POSTGRES_DB: scoap3
          POSTGRES_USER: scoap3
          POSTGRES_PASSWORD: scoap3
        ports:
          - 5432:5432
      mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
          - '8025:8025'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Test
        run: >
          docker run
          --pull always
          --network="host"
          --env POSTGRES_DB=scoap3
          --env POSTGRES_USER=scoap3
          --env POSTGRES_PASSWORD=scoap3
          --env POSTGRES_HOST=localhost
          ${{ inputs.image }}
          pytest
